name: AtCoder Sync

on:
  schedule:
    - cron: '0 0 * * *' # 毎日日本時間の朝9時に実行
  workflow_dispatch: # 手動で実行したい時用

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: AtCoder Sync
        uses: asf79/atcoder-problems-sync-action@v2
        with:
          atcoder-user-id: 'sam_el'
          github-token: ${{ secrets.GH_TOKEN }}
          # 過去の分を全部持ってくるなら以下をコメントアウト解除
          # crawl-all: true
