name: AtCoder Sync

on:
  schedule:
    - cron: '0 0 * * *' # 毎日日本時間の朝9時に実行
  workflow_dispatch: # 手動で実行したい時用

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: AtCoder Sync
        # ここを修正しました！
        uses: asf79/atcoder-sync@v2
        with:
          atcoder-user-id: 'sam_el' 
          github-token: ${{ secrets.GH_TOKEN }}
          # 初めて動かす時は、下の「#」を消すと過去の全ACを持ってこれます
          crawl-all: true
